In [1]:
import pandas as pd
import numpy as np
file_map ='cable_mapping_07.06.2018.xlsx'

import os
home_path = os.getcwd().replace('/BC1/notebooks','')

In [2]:
# Load spreadsheet
file_xlsx=home_path+'/processed_data/Dados BC1/'+file_map

In [3]:
def create_pixel_map(map_file):
    """
    Create the array with the mapping for each
    MA-PMT anode.
    Arguments:
    ---------
    map_file : (str)
        Complete path to the mapping file provided by
        the Cs Group.
    Returns:
    -------
    pixel_map : 2D array
        Array with the 8x8 grid of pixels mapped to
        channel numbers.
    """
    # load spreadsheet as a pandas dataframe
    df = pd.read_excel(map_file)
    pmt_channel = df['MaPMT channel']
    pmt_channel = pmt_channel.append(df['MaPMT channel.1'], ignore_index=True)
    pmt_block = df['PMT block slot']
    pmt_block = pmt_block.append(df['PMT block slot.1'], ignore_index=True)
    # load and fill pixel map
    pixel_map = np.zeros(64)
    for i, pixel in enumerate(pmt_channel):
        if np.isnan(pixel):
            continue
        else:
            pixel_map[int(pixel) - 1] = pmt_block[i]
    # reshape the array in the 8x8 grid
    pixel_map = pixel_map.reshape((8, 8))
    return pixel_map

In [4]:
print create_pixel_map(file_xlsx)

[[ 0.  0.  0. 48. 46.  0.  0.  0.]
 [ 0. 44. 42. 40. 38. 36. 34.  0.]
 [19. 32. 30. 28. 26. 23. 25.  0.]
 [27. 29. 31. 33. 35. 37. 39. 41.]
 [43. 45. 47. 24. 22. 20. 18. 16.]
 [ 0. 14. 12.  8.  6.  5. 10. 21.]
 [ 0.  1.  2.  9. 17.  7. 11.  0.]
 [ 0.  0.  0. 13. 15.  0.  0.  0.]]


In [5]:
np.savetxt(home_path+'/processed_data/Dados BC1/pixel_map',create_pixel_map(file_xlsx),fmt='%i', delimiter=' ')